### ISSUE TITLE
公式（3）（6）

### ISSUE THREAD

**Issue by qiunlp** [BenfengXu/SSAN#1]
请问论文中公式（3）（6)的出处在哪里？谢谢！

**Comment by BenfengXu** [comment]
> 请问论文中公式（3）（6)的出处在哪里？谢谢！

请问这里是指：方法的出处 or 代码实现的出处？
如果是前者，公式（3）（6）是我们在SSAN这篇文章中提出的方法，以建模实体的交互结构；
如果是后者，请参考`./model/modeling_bert.py#L267-L280.`，如README中所提到。

**Comment by qiunlp** [comment]
非常感谢你的答复。就是说公式（3）是你们的创新。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月22日(周一) 下午2:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BenfengXu/SSAN] 公式（3）（6） (#1)




  
请问论文中公式（3）（6)的出处在哪里？谢谢！
  
请问这里是指：方法的出处 or 代码实现的出处？
 如果是前者，公式（3）（6）是我们在SSAN这篇文章中提出的方法，以建模实体的交互结构；
 [如果是后者，请参考./model/modeling_bert.py#L267-L280.，如README中所提到。

**Comment by BenfengXu** [comment]
> 非常感谢你的答复。就是说公式（3）是你们的创新。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年3月22日(周一) 下午2:56 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [BenfengXu/SSAN] 公式（3）（6） (#1) 请问论文中公式（3）（6)的出处在哪里？谢谢！ 请问这里是指：方法的出处 or 代码实现的出处？ 如果是前者，公式（3）（6）是我们在SSAN这篇文章中提出的方法，以建模实体的交互结构； [如果是后者，请参考./model/modeling_bert.py#L267-L280.，如README中所提到。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是的，Biaffine Transformation的结构（3）（6）是我们提出的设计，Decomp Transformation的结构（7）则是在一定程度上受到了之前一些相关领域的工作的启发（Dai et al. 2019 ）（Shaw, Uszkoreit, and Vaswani 2018)）

Dai, Z., Yang, Z., Yang, Y., Carbonell, J., Le, Q. V., & Salakhutdinov, R. (2019). Transformer-xl: Attentive language models beyond a fixed-length context. arXiv preprint arXiv:1901.02860.
Shaw, P., Uszkoreit, J., & Vaswani, A. (2018). Self-attention with relative position representations. arXiv preprint arXiv:1803.02155.
