### ISSUE TITLE
你好，得到result.json 文件后，这个文件该如何理解？

### ISSUE THREAD

**Issue by eve1104** [BenfengXu/SSAN#11]
{"title": "Miguel Riofr\u00edo", "h_idx": 0, "t_idx": 1, "r": "P569", "evidence": []} 我得到title: "Miguel Riofr\u00edo 有多个，他们是哪一句在哪里体现？得到的文件究竟该如何理解？

**Comment by BenfengXu** [comment]
每一条数据应该包含 title / vertexSet / sents 等字段，可以按照title去检索到对应的数据，这个应该是唯一的
"h_idx"代表subject实体在 vertexSet字段中的 index，即vertexSet[h_idx]
同理t_idx，据此可索引到对应的实体，以及找到它们在段落、句子中的位置
"r"代表对应的关系

**Comment by eve1104** [comment]
Thank you for answering my question.

**Comment by YuanEric88** [comment]
请问result.json这个数据结构的设计出于什么考虑的呢？当前的结果中每一个element是一个实体词对的分类结果，为什么不以title为单位进行存储，也就是一个element包含了一个title中所有的实体词对分类信息？现在的存储方式看起来相对杂乱

**Comment by BenfengXu** [comment]
> 请问result.json这个数据结构的设计出于什么考虑的呢？当前的结果中每一个element是一个实体词对的分类结果，为什么不以title为单位进行存储，也就是一个element包含了一个title中所有的实体词对分类信息？现在的存储方式看起来相对杂乱

和官方Baseline的实现以及Codalab榜单的提交要求一致的哈，请参考：
https://github.com/thunlp/DocRED
https://competitions.codalab.org/competitions/20717#results
