### ISSUE TITLE
Empty Evidence List

### ISSUE THREAD

**Issue by snehasinghania** [BenfengXu/SSAN#12]
Hi, 

Congratulations on your great work!

I ran the predict.sh code for the results on the test.json. The results.json is created but the evidence for an identified relation is an empty list. Could you explain why that happens?

**Comment by BenfengXu** [comment]
Yes, our relation extraction model do not use or predict the evidence slot, as you can see on the leaderboard, the Evi_F1 of SSAN is 0.0, the empty list is created only for valid result formation check.
The evidence annotation was provided in the DocRED dataset as an auxiliary task, which is not explored in our work, you can refer to other works that included this.

Thanks for your attention on our work~

**Comment by snehasinghania** [comment]
Thanks for the reply! That was helpful :+1:
