### ISSUE TITLE
What is the computational complexity of the ATLOP model?

### ISSUE THREAD

**Issue by ThinkNaive** [BenfengXu/SSAN#16]
I tried to analyze the computational complexity of the ATLOP model but failed because I cannot handle the computational complexity of BERT finetune procedure. Could you please tell me the result? Thank you.

**Comment by BenfengXu** [comment]
> I tried to analyze the computational complexity of the ATLOP model but failed because I cannot handle the computational complexity of BERT finetune procedure. Could you please tell me the result? Thank you.

ATLOP is not included in this repo, you should instead discuss at [here](https://github.com/wzhouad/ATLOP/issues/29)
