### ISSUE TITLE
关于远程监督数据集上的预训练模型训练情况

### ISSUE THREAD

**Issue by zhongy1026** [BenfengXu/SSAN#18]
想请教作者，在远程监督数据集上的预训练模型训练了多久，GPU使用情况如何，期待您的回复，谢谢

**Comment by BenfengXu** [comment]
> 想请教作者，在远程监督数据集上的预训练模型训练了多久，GPU使用情况如何，期待您的回复，谢谢

您好，感谢关注我们的工作。epoch=10, lr=2e-5, bs=4,。GPU为单卡V100，和在训练集上一致。可参考Arxiv版本论文中的Appendix~

**Comment by zhongy1026** [comment]
谢谢，还有三个问题需要请教您：1、在一张V100训练了多长时间呢/2、模型参数是随机初始化的还是在已有模型参数的基础上训练/3、预训练部分能不能发布代码，或者您预训练所参考的代码链接

**Comment by BenfengXu** [comment]
> 谢谢，还有三个问题需要请教您：1、在一张V100训练了多长时间呢/2、模型参数是随机初始化的还是在已有模型参数的基础上训练/3、预训练部分能不能发布代码，或者您预训练所参考的代码链接

1.不好意思，这个具体时间记不清了。
2.使用BERT / RoBERTa初始化，先在distant上预训练，再在trainset上训练
3.预训练代码和trainset上训练的代码是一致的，直接把数据集文件替掉即可（注意distant中好像有一条数据不含有实体，可能需要提前remove，否则会报错）。

**Comment by zhongy1026** [comment]
谢谢
