### ISSUE TITLE
请问dataset.py中的distance_buckets 的值是怎么确定出来的？

### ISSUE THREAD

**Issue by LawsonAbs** [BenfengXu/SSAN#19]
我们知道，`distance_buckets` 是用于计算各个实体之间的相对距离，但是这个`distance_buckets`中的值是怎么获取的呢？就是下面这一部分代码：
` distance_buckets[1] = 1 
    distance_buckets[2:] = 2
    distance_buckets[4:] = 3
    distance_buckets[8:] = 4
    distance_buckets[16:] = 5
    distance_buckets[32:] = 6
    distance_buckets[64:] = 7
    distance_buckets[128:] = 8
    distance_buckets[256:] = 9
`

**Comment by kgresearch** [comment]
> 我们知道，`distance_buckets` 是用于计算各个实体之间的相对距离，但是这个`distance_buckets`中的值是怎么获取的呢？就是下面这一部分代码： `distance_buckets[1] = 1 distance_buckets[2:] = 2 distance_buckets[4:] = 3 distance_buckets[8:] = 4 distance_buckets[16:] = 5 distance_buckets[32:] = 6 distance_buckets[64:] = 7 distance_buckets[128:] = 8 distance_buckets[256:] = 9`

distance_buckets中的值是按照规则预先设定的，直觉上实体对之间的相对距离对其相关性的影响不应该是线性的，因此这里使用了指数距离来刻画，即比较近的distance划分粒度更细致，比较远的distance划分粒度更粗糙。
这个实现参考了官方的baseline：
[https://github.com/thunlp/DocRED/blob/master/code/config/Config.py#L82:L91](https://github.com/thunlp/DocRED/blob/master/code/config/Config.py#L82:L91)

**Comment by BenfengXu** [comment]
> 我们知道，`distance_buckets` 是用于计算各个实体之间的相对距离，但是这个`distance_buckets`中的值是怎么获取的呢？就是下面这一部分代码： `distance_buckets[1] = 1 distance_buckets[2:] = 2 distance_buckets[4:] = 3 distance_buckets[8:] = 4 distance_buckets[16:] = 5 distance_buckets[32:] = 6 distance_buckets[64:] = 7 distance_buckets[128:] = 8 distance_buckets[256:] = 9`

distance_buckets中的值是按照规则预先设定的，直觉上实体对之间的相对距离对其相关性的影响不应该是线性的，因此这里使用了指数距离来刻画，即比较近的distance划分粒度更细致，比较远的distance划分粒度更粗糙。
这个实现参考了官方的baseline：
[https://github.com/thunlp/DocRED/blob/master/code/config/Config.py#L82:L91](https://github.com/thunlp/DocRED/blob/master/code/config/Config.py#L82:L91)

**Comment by LawsonAbs** [comment]
感谢回复，原来是参考了DocRED那里的baseline， 是我疏忽了~
