### ISSUE TITLE
论文中的疑惑点

### ISSUE THREAD

**Issue by chenhaishun** [BenfengXu/SSAN#2]
同学你好，在这篇论文中有些许疑惑，想请教一下：
在“Entity Structure Within and Throughout: Modeling Mention Dependencies for Document-Level Relation Extraction“论文中，
论文的主要创新点在于formulate了一个可以反映文档结构的entity-centric adjacency matrix, 在2.3小节也提到"我们利用特定的参数实例化了此矩阵中的元素"，并在之后介绍了两种Transformation module。我想知道在此处是如何将adjacency matrix中的元素实例化为具有特定意义的神经层参数的呢？这个实例化过后的矩阵的信息是否包含在公式（6）中的A或公式（7）中的K，Q呢？是否在此过程中结构信息是否有所损失呢？

期待你的回复！

**Comment by BenfengXu** [comment]
> 同学你好，在这篇论文中有些许疑惑，想请教一下：
> 在“Entity Structure Within and Throughout: Modeling Mention Dependencies for Document-Level Relation Extraction“论文中，
> 论文的主要创新点在于formulate了一个可以反映文档结构的entity-centric adjacency matrix, 在2.3小节也提到"我们利用特定的参数实例化了此矩阵中的元素"，并在之后介绍了两种Transformation module。我想知道在此处是如何将adjacency matrix中的元素实例化为具有特定意义的神经层参数的呢？这个实例化过后的矩阵的信息是否包含在公式（6）中的A或公式（7）中的K，Q呢？是否在此过程中结构信息是否有所损失呢？
> 
> 期待你的回复！

你好！欢迎关注我们的工作~
    实例化是指，我们把adajacency matrix中的元素与新引入的trainable 网络模块组一一对应起来。我们一共设计了五种dependency，分别对应matix中的五种元素，然后分别对应每一个Transformer layer每一个attention head中的五个A矩阵。当这种对应关系建立起来之后，网络在训练过程中会在loss的指导下自行尝试去建模、捕捉相关的信息。我们只需要将这些新引入的A、K、Q 矩阵/向量随机初始化，然后通过在不同的训练数据中根据结构matrix去调用不同的module，训练他们即可。
    在这个过程中是否有损失？因为这部分结构信息是辅助性的，我们无法准确地定义他们对于最终的结果的作用的上限，只能尽可能地设计更优的结构去建模它们，因为本质上还是用深度网络去拟合数据，而不是严格地数学推导，所以我想肯定是没法完美地把这部分结构信息利用好的，但是从结构来看，SSAN是能提高performance的，这在一定程度上验证了我们的设计。
    以及，关于之前邮件的回复（2021年03月22日 16:10:23 (星期一)已回复），请check你的邮箱哈，是不是被挡在垃圾箱里了~
