### ISSUE TITLE
Model Parameters Size?

### ISSUE THREAD

**Issue by jzhang38** [BenfengXu/SSAN#24]
Hi,

Congratulations on your great work!

May I know they model size of SSAN? I feel that substantial amount of additional parameters are added to the backbone (BERT/RoBerta) due to the Transformation Module. Is this true?

Thank you!

**Comment by BenfengXu** [comment]
The additional paramters of SSAN mainly come from transformation matrix A, and its bias b (see eq. 6).

For Biaffine Transformation, A is of dim_per_head * dim_per_head, and the new paramters in total are caculated as:
N = (dim_per_head * dim_per_head + 1) * n_head * n_layer * n_structure
in the original paper, n_structure=5, so for BERT / RoBERTa Base, N=(64 * 64 + 1) * 12 * 12 * 5=2.9M, comparing to BERT's original parameter of 110M, so SSAN adds approximately 2.6% new parameters.

For Decomposed Linear Transformation, similarly we get N=(2 * dim_per_head + 1) * n_head * n_layer * n_structure=0.09M, which is much smaller, so SSAN_Decomposed adds approximately 0.08% new paramters.

Actually, we can still share the transformation module across different heads, or even different layers, reduce X12 its parameters, but I can only guss this will not significant affect its performance.

Hope this helps, if the above calculation went wrong or you have further regarding questions, let me know.
