### ISSUE TITLE
请问如何处理文本长度大于512的

### ISSUE THREAD

**Issue by Yesgo1220** [BenfengXu/SSAN#3]
在论文中没有看出来作者如何处理长文本的，如大于512的

**Comment by BenfengXu** [comment]
> 在论文中没有看出来作者如何处理长文本的，如大于512的

DocRED中tokenization之后大于512的数据非常少，因此我们直接将其截断。

**Comment by Yesgo1220** [comment]
感谢快速的回答，工作很棒！
